"""
Workaround for Pylance not recognizing Python built-ins.
Import this module in files that have issues with built-in functions.
"""

# Re-export all commonly used built-ins that Pylance sometimes doesn't recognize
from builtins import (
    abs,
    all,
    any,
    bin,
    bool,
    callable,
    chr,
    classmethod,
    delattr,
    dict,
    divmod,
    enumerate,
    filter,
    float,
    getattr,
    hasattr,
    hash,
    hex,
    id,
    input,
    int,
    isinstance,
    issubclass,
    len,
    list,
    map,
    max,
    min,
    oct,
    open,
    ord,
    pow,
    print,
    property,
    range,
    repr,
    reversed,
    round,
    set,
    setattr,
    sorted,
    staticmethod,
    str,
    sum,
    super,
    tuple,
    type,
    zip,
)

__all__ = [
    'all', 'any', 'dict', 'list', 'tuple', 'set', 'str', 'int', 'float', 'bool',
    'len', 'max', 'min', 'sum', 'abs', 'round', 'sorted', 'reversed',
    'getattr', 'setattr', 'hasattr', 'delattr', 'isinstance', 'issubclass',
    'property', 'staticmethod', 'classmethod', 'super',
    'enumerate', 'zip', 'map', 'filter', 'range',
    'print', 'input', 'open', 'type', 'callable', 'id', 'repr', 'hash',
    'chr', 'ord', 'bin', 'hex', 'oct', 'divmod', 'pow'
]
