# UPL Compliance Contract v1.0.0
version: 1.0.0
last_updated: 2024-01-15
enforcement_mode: strict  # strict|permissive|audit_only

actions:
  - id: Explain
    category: informational
    risk_level: low
    description: "Provide general legal information without application"

  - id: DefineTerms
    category: informational
    risk_level: low
    description: "Define legal terminology"

  - id: OutlineOptions
    category: informational
    risk_level: medium
    description: "Present available legal pathways without recommendation"

  - id: SelectForm
    category: guidance
    risk_level: high
    description: "Recommend specific legal form or document"

  - id: GiveFilingSteps
    category: procedural
    risk_level: medium
    description: "Provide court filing procedures"

  - id: InterpretStatute
    category: analysis
    risk_level: critical
    description: "Apply law to specific facts"

  - id: RecommendStrategy
    category: advice
    risk_level: critical
    description: "Suggest legal strategy or approach"

allow_matrix:
  Explain:
    default: allowed
    rationale: "General information is First Amendment protected"
    conditions: []

  DefineTerms:
    default: allowed
    rationale: "Dictionary definitions are public knowledge"
    conditions: []

  OutlineOptions:
    default: conditional
    rationale: "Must present all options neutrally"
    conditions:
      - type: disclaimer_required
        text: "This is general information only. Consult an attorney for advice about your specific situation."
      - type: neutrality_check
        validator: verify_no_recommendation

  SelectForm:
    default: deny
    rationale: "Form selection constitutes legal advice"
    mitigation_template: |
      I cannot recommend specific legal forms. You may:
      - Consult with a licensed attorney in {jurisdiction}
      - Visit your local law library for self-help resources
      - Contact the {jurisdiction} Bar Association referral service

  GiveFilingSteps:
    default: conditional
    rationale: "Procedural information allowed if jurisdiction-specific"
    conditions:
      - type: jurisdiction_required
        fallback: deny
      - type: disclaimer_required
        text: "Court procedures vary. Verify current requirements with the clerk's office."

  InterpretStatute:
    default: deny
    rationale: "Legal interpretation requires bar admission"
    mitigation_template: |
      I cannot interpret how laws apply to specific situations.
      For legal interpretation, please consult a licensed attorney.

  RecommendStrategy:
    default: deny
    rationale: "Strategic advice is core legal practice"
    mitigation_template: |
      Legal strategy requires professional judgment. Please consult
      with an attorney licensed in {jurisdiction}.

triggers:
  high_risk_verbs:
    - pattern: '\b(should\s+I|what\s+should|ought\s+to|must\s+I)\b'
      weight: 0.8
      intent: advice_seeking

    - pattern: '\b(file|serve|plead|argue|claim|sue|defend)\b'
      weight: 0.7
      intent: action_planning

    - pattern: '\b(my\s+case|my\s+situation|my\s+landlord|my\s+employer)\b'
      weight: 0.6
      intent: specific_application

  safer_patterns:
    - pattern: '\b(what\s+is|definition\s+of|explain|how\s+does.*work)\b'
      weight: -0.5
      intent: informational

    - pattern: '\b(generally|typically|usually|commonly)\b'
      weight: -0.3
      intent: general_information

mitigations:
  standard_referral:
    template: |
      For legal advice specific to your situation, please consult with
      a licensed attorney in {jurisdiction}. You can find attorneys through:
      - {bar_referral_url}
      - {legal_aid_url}
      - {court_self_help_url}

  form_assistance:
    template: |
      While I cannot select forms for you, {court_name} provides
      self-help resources at {self_help_url}. Court clerks can provide
      procedural information but cannot give legal advice.

  emergency_referral:
    template: |
      If this is an emergency or involves immediate harm:
      - Call 911 for immediate danger
      - Contact {domestic_violence_hotline} for DV situations
      - Reach {legal_aid_emergency} for urgent legal help
