name: Block merge conflict markers
on:
  pull_request:
  push:
    branches: ["**"]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files (PR or push)
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git fetch --no-tags --prune --depth=2 origin ${{ github.base_ref }}
            base="${{ github.event.pull_request.base.sha }}"
            head="${{ github.sha }}"
          else
            base="$(git rev-parse HEAD^ || echo '')"
            head="$(git rev-parse HEAD)"
          fi
          if [ -n "$base" ]; then
            git diff --name-only "$base" "$head" > changed.txt
          else
            git ls-files > changed.txt
          fi
          # Filter to text files only
          : > text_changed.txt
          while IFS= read -r f; do
            [ -f "$f" ] || continue
            if file -I "$f" | grep -q "text/"; then echo "$f" >> text_changed.txt; fi
          done < changed.txt
          echo "Changed text files:"
          cat text_changed.txt || true
      - name: Scan for conflict markers
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -s text_changed.txt ]; then
            echo "No text files changed."
            exit 0
          fi
          if xargs -a text_changed.txt grep -I -n -E '^(<{7}|={7}|>{7})' -- ; then
            echo "::error::Conflict markers detected in changed files."
            exit 1
          else
            echo "✅ No conflict markers found."
          fi
