name: Purge Quarantine
on:
  schedule:
    - cron: '17 5 * * 1'
  workflow_dispatch: {}
jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Purge .quarantine older than 7 days
        run: |
          python3 - <<'PY'
          from pathlib import Path
          from datetime import datetime, timedelta
          import shutil
          root = Path('.').resolve() / '.quarantine'
          cutoff = datetime.utcnow() - timedelta(days=7)
          if root.exists():
              for d in root.iterdir():
                  try:
                      ts = datetime.strptime(d.name, "%Y%m%dT%H%M%SZ")
                  except Exception:
                      continue
                  if ts < cutoff:
                      shutil.rmtree(d, ignore_errors=True)
          PY
